plesk/centos2alma

actions/common.py

Found in scope of #89. Might be related, but I'm not sure.

Handle selinux only if it exists and enabled

---

actions/common_checks.py

Hide domain switching step if there are no domains related to outdated PHP

---

actions/mariadb.py
actions/systemd.py
main.py

Update mariadb before start it as plesk database

---

common/version.py
tests/versiontests.py

Fix build part comparation for kernel versions

---

actions/installation.py
actions/mariadb.py

Remove compat packages to avoid conflicts on new package installation

---

actions/common_checks.py

Take kernel-plus and kernel-rt-core packages for kernel version checker

---

actions/systemd.py

Related issues are #176 and #177

Check postfix exists

---

actions/common.py
actions/packages.py
main.py

Recreate awstats config after conversion done

---

actions/packages.py

Make libwebp7, libzip5 and libytnef as reinstallable conflict packages

---

actions/php.py
main.py

Check php provided by os vendor is in use

---

actions/mariadb.py
actions/packages.py
main.py

Add action for mapping atomic repositories

---

actions/installation.py

Remove leapp-upgrade-el7toel8 package on finishing stage

---

centos2almaconverter/actions/extensions.py
centos2almaconverter/upgrader.py

PPP-64910. This will need to be released with or before Plesk 18.0.62.
Depends on https://github.com/plesk/dist-upgrader/pull/39

TuxCare ELS support and minor fixes

---

centos2almaconverter/upgrader.py

Conversion with the extension is not supported yet

Prevent conversion when LiteSpeed extension is installed

---

README.md
centos2almaconverter/actions/packages.py
centos2almaconverter/upgrader.py

Support rackspace epel

---

README.md

Avoid mysqld problem for plesk services

---

README.md
centos2almaconverter/actions/convert.py
centos2almaconverter/upgrader.py

Make it possible to rule LEAPP_OVL_SIZE

---

centos2almaconverter/upgrader.py

Reinstalled Amavis antivirus from plesk email security extension

---

centos2almaconverter/actions/configure.py
centos2almaconverter/actions/packages.py

Dont ignore php56 php70 on adoption

---

centos2almaconverter/upgrader.py

Disable the firewalld systemd service if the plesk-firewall service is installed and in use

---

centos2almaconverter/actions/installation.py

Remove all system_upgrade links from leapp repos directory

---

centos2almaconverter/actions/installation.py

Pin Leapp-deps and Leapp-upgrade packages to prevent script from breaking during updates

---

centos2almaconverter/actions/perl.py

Add some more mapping for known perl modules

---

centos2almaconverter/actions/packages.py
centos2almaconverter/upgrader.py

Introduce an action to create a leapp mapping and abopt it on finishing stage

---

centos2almaconverter/actions/extensions.py
centos2almaconverter/actions/mariadb.py
centos2almaconverter/actions/packages.py
centos2almaconverter/upgrader.py

Download missing plesk gpg keys for leapp configuration

---

centos2almaconverter/actions/extensions.py

This addresses a specific issue with certain repositories provided by Immunify extensions. While yum handles these repositories correctly using credentials configured by the extensions, Leapp upgrade process lacks access to those credentials and gets stuck when trying to retrieve packages due to GPG key authentication prompts.
To work around this, we now extract the required GPG key from the local RPM database and provide it to Leapp manually.

Use GPG key from local RPM database to avoid fetching password-protected remote key
