plesk/centos2alma

actions/common.py
main.py

As Plesk services are stopped during the conversion, the banner information can be misleading.

Disable Plesk banner for SSH during the conversion process

---

common/leapp_configs.py

The right mapping for rackspace repositories is rhel8, not centos8.

Fix rackspace repositories mapping

---

actions/common.py
common/messages.py
main.py

Related issue #89 ([comment](https://github.com/plesk/centos2alma/issues/89#issuecomment-1534819859))

Introduce a 45-second delay before the initial reboot

---

.github/workflows/build.yml
.github/workflows/tests.yml
BUCK
build/Dockerfile
tests/rpmtests.py

Encountered issues with OpenJDK installation on Azure instances. It appears that some packages are missing on their side. Since I was planned to provide Dockerfile for build anyway, let's move to docker based build on actions as well.

Migrate to Docker-based Buck build to ensure Buck installation is fine

---

actions/common.py
main.py

Due to AlmaLinux 8 using rsyslog instead of syslog, we cannot utilize the syslog logrotate configuration. Unfortunately, Elevate is unable to replace the configuration during the conversion process itself. Therefore, we need to manually make the necessary changes.

Replace the logrotate configuration for syslog with a similar configuration for rsyslog after the conversion

---

common/leapp_configs.py
tests/leapp_configs_tests.py

There is not centos8-* repositories since MariaDB 10.11. Therefore, we need to switch to either RHEL8 or "centos/8/*". While there isn't much difference between them,
moving to RHEL8 seems simpler, so I decided to use it.

Move MariaDB to the rhel8 repository instead of centos8 during conversion

---

actions/installation.py

Related problem was firstly described in #166

Disable elivate repository to avoid detecting outdated version by prechecker and accedent update of the leapp packages

---

actions/common_checks.py

Since KernelVersion now could parce versions with any prefixes like "kernel-", "kernel-rt-", "kernel-plus-", we can just pass row names of rpm packages.

Support kernel-plus, kernel-rt and other specific kernels

---

actions/common.py

Since process has been started from scratch, we should remove previous in-progress message and fill it from the scratch

Restore original message of the day, before making in progress message

---

actions/configure.py
main.py

Patch the leapp package signature checker to prevent errors when writing non-ASCII string into logs

---

actions/__init__.py
actions/emails.py
main.py

Since we moves to roundcube 1.6 after the conversion, we have to increase size of DH parameters. Othervise it seems like roundcube refuses the connection.

Increase size of DH parameters to at least 2048 bit for dovecot

---

actions/packages.py

Append the recently removed conflict packages instead of overwriting to prevent issues if centos2alma server is started multiple times

---

actions/emails.py

In some cases sslmng output could skip parameters for specific services. Usually it happens when ssl related parameters was not specifically changed for a service. This situation is fine, so we should just skip the DH parameters increase action in this case.

Handle parce exceptions carefully on checking sslmng output

---

centos2almaconverter/actions/common_checks.py
centos2almaconverter/upgrader.py

Unfortiantly, leapp prevents conversion if there is no kernel packages provided by RedHat.
They also checks if package signed by RedHat, however it looks like check if packages are installed is good enougth.

Check if kernel provided by RedHat at least installed.

---

centos2almaconverter/actions/common.py

This likely indicates that awstats was removed
Related issue is #267

Skip RecreateAwstatConfigurationFiles if there is no required file for awstat configuration creation

---

README.md

Requirements: Plesk version should be LESS than five releases behind the latest version, not MORE

Fix typo in README.md (requirements)

---

centos2almaconverter/upgrader.py

We are going to introduce PHP 5.6 support for AlmaLinux 8. This version will be provided by Plesk to assist customers transitioning from CentOS 7. Consequently, we can now allow conversion when PHP 5.6 is installed and in use.

Enable conversion when PHP 5.6 is installed

---

centos2almaconverter/actions/packages.py
centos2almaconverter/upgrader.py

Certain repositories (like custom ELS for Centos 7) can cause failures in dnf on AlmaLinux 8. Therefore, we need to stop conversion in these cases

Add a feature to block conversion if the repository's source is an IP address

---

centos2almaconverter/actions/packages.py

Address potential conflicts caused by the prohibition of package downgrades in dnf. This is due to the higher package versions present in CentOS 7 compared to AlmaLinux 8, which could disrupt the conversion process.

Prevent leapp issues by removing libidn2 and lua-socket prior to conversion

---

centos2almaconverter/upgrader.py

Leapp specifically requires GRUB2 for correct operation; otherwise, it will block the conversion

Use GRUB2 installed pre-checker instead of checking for any GRUB installation

---

centos2almaconverter/upgrader.py

Leapp cannot handle conversion if multiple kernel-devel packages are present, so we need to verify this on our end

Added an assertion to ensure only one kernel-devel package is installed

---

.gitmodules

Bring in recent changes from dist-upgrader.
Also, switch its URL to HTTPS. It's more convenient, because it doesn't require an SSH key.

Update the dist-upgrader submodule, switch to HTTPS

---

centos2almaconverter/actions/packages.py
centos2almaconverter/upgrader.py

Fixes PAUX-6347: centos2alma fails when plesk was originally installed from archive

FIX add checking .autoinstallerrc for archive SOURCE

---

centos2almaconverter/upgrader.py

We will now skip any interactions with the mailman service if it is not active at the start of the conversion.
By default, mailman is not configured and the service will fail to start. Therefore, attempts to start it during the revert or finishing stage will also fail.

Handle mailman systemd service in separate action

---

centos2almaconverter/actions/packages.py

Old message was like:
```
[root@ip-10-69-45-162 ~]# ./centos2alma 
Doing preparation checks...
Required pre-conversion condition 'checking if all packages are up to date' not met:
There are packages which are not up to date. Call `yum update -y && reboot` to update the packages.
Required pre-conversion condition 'checking if SOURCE points to old archive' not met:
Old archive doesn't serve up-to-date Plesk.
Edit {self.AUTOINSTALLERRC_PATH} and change SOURCE - i.e. https://autoinstall.plesk.com
Conversion can't be performed due to the problems noted above

Fix message when autoinstallerrc has Plesk archive SOURCE

---

centos2almaconverter/actions/packages.py

Even though CentOS 7 has libidn2-2.3.7-1.el7.x86_64, which is higher than AlmaLinux 8 version libidn2-2.2.0-1.el8.x86_64, it is correctly downgraded on conversion.
Note that missing libidn2 might cause issues with dnf operation in case upgraded libcurl is used.
Removal was originally added in 78ff7d93692a5ef2fc305fb75de8395af294faa6.

Don't remove libidn2 prior to conversion.

---

README.md

I found out that the `-s finish` flag does not work when the process fails after the first reboot.
Instead the `--resume` flag should work.

Point to --resume when the process fails after reboot

---

centos2almaconverter/upgrader.py

RAID devices might get renamed after the conversion, causing issues with mounting and potentially leading to boot problems for a converted host.

Use pre-checker to avoid conversion when there is RAID devices in /etc/fstab

---

centos2almaconverter/actions/extensions.py
centos2almaconverter/upgrader.py

This action retrieves the KernelCare GPG key from the configured repository specifically for leapp. Normally, leapp includes all necessary GPG keys within a designated configuration directory. However, since KernelCare is not supported by AlmaLinux, we must manually fetch the GPG key to ensure leapp can proceed with the conversion when KernelCare repository packages are installed.

Introduce FetchKernelCareGPGKey action to obtain the GPG key for the leapp utility

---

centos2almaconverter/actions/installation.py
centos2almaconverter/upgrader.py

If there's an issue during the conversion but it still passes overall, it's unreasonable to expect someone to repeat the process just to obtain logs of leapp. Therefore, keeping them by default is better.

Keep logs of leapp by default

---

centos2almaconverter/upgrader.py

Some of our services depends on openssl. So we should be sure it's installed, before starting this services.

Re-install conflict packages before starting basic plesk services
